### ISSUE TITLE
Issue with typescript definition and reference to d3

### ISSUE THREAD

**Issue by darewreck54** [microsoft/powerbi-visuals-utils-svgutils#18]
In d3 version 4.13, the definition for this library is not compatible.  

d3.Selection<any> has changed to d3.Selection<any,any,any,any>;

Is there anyway to not put a version dependency on this library or is there an implied dependency.

Thanks,
Derek

**Comment by uve** [comment]
@darewreck54, try to use d3 version 3.
Or there is an alternative option to use types for d3-selection:
https://www.npmjs.com/package/@types/d3-selection
